export default class CONSTANTS {
  public static readonly MESSAGES = {
    ERR_URL_NOT_FOUND: 'URL not found.',
    INTERNAL_SERVER: 'Something went wrong!',
    BULK_IMPORT_FILE_VALID: 'Please upload valid file!',
    IMPORT_SUCCESS: 'Data Imported Successfully',
    NOT_RECORD_FOUND: 'No record found.',
    UNAUTHORIZED: 'Unauthorized.',
    ACCESS_DENIED: 'Access denied.',
    SERVICE_RUN: 'Service is running.',
    CREATE_SUCCESS: 'Created successfully.',
    INVALID_CREDENTIALS: 'Incorrect email or password.',
    INVALID_PASSWORD: 'Incorrect old password.',
    INCORRECT_PASSWORD: 'Incorrect password.',
    PASSWORD_RESET_SUCCESS: 'Password reset successfully.',
    TOKEN_EXPIRED: 'Token was expired.',
    LOGIN_SUCCESS: 'You have successfully logged in!',
    SIGNUP_SUCCESS: 'Registration successful!',
    LOGOUT_SUCCESS: 'You have successfully logged out!',
    TOKEN_REQUIRED: 'You are not authorized.',
    FIRST_NAME: 'The first name should not exceed 25 characters.',
    NAME: 'The name should not exceed 25 characters.',
    LAST_NAME: 'The last name should not exceed 25 characters.',
    MIDDLE_NAME: 'The middle name should not exceed 25 characters.',
    EMAIL_NAME: 'The email should not exceed 320 characters.',
    PAYMENT_MODE: 'The payemnt mode should not exceed 20 characters.',
    CONTACT_NUMBER_VALID: 'The contact number can only contain numbers.',
    NAME_STRING_CHECK: 'can only contain letters and spaces',
    INAVLID_TOKEN: 'Invalid token.',
    DEVICE_ACCESS:
      'Based on your subscription, limit exceeded for multiple logins. Please log out from other devices!',
    UPDATE_SUCCESS: 'Record updated successfully.',
    UPDATE_STATUS_SUCCESS: 'Status updated successfully.',
    INTERNAL_SERVER_ERROR: 'Something went wrong!',
    SUCCESS: 'Record fetched successfully.',
    RECORD_DELETE_SUCCESS: 'Record deleted successfully.',
    BOOKMARK_DELETE_SUCCESS: 'Bookmark deleted successfully.',
    RECORD_DELETE_FAILED: 'Record delete failed.',
    RECORD_ADDED_SUCCESS: 'Record added successfully.',
    BOOKMARK_ADDED_SUCCESS: 'Bookmark added successfully.',
    RECORD_REMOVE_SUCCESS: 'Record removed successfully.',
    UPDATE_RECORD_FAIL: 'Record update failed.',
    SUBSCRIPTION_NOT_FOUND: 'Subscription details not found. Please try again',
    SUBSCRIPTION_UPDATED: 'Your Subscription Has Been Renewed!',
    SUBSCRIPTION_UPDATED_FAILED: 'Subscription Update Failed!',
    DEVICE_LIMIT:
      'Your device limit is reached please logout in onther device and after try to login',

    EMAIL_INVALID: 'Invalid email.',
    PROJECT_NAME_INVALID: 'Invalid project name',
    PROGRAM_NAME_INVALID: 'Invalid program name',
    IMG_SUCCESS: 'Image upload Successfully',
    VIDEO_SUCCESS: 'Video upload Successfully',
    INACTIVE_USER: 'Inactive user.',
    INACTIVE_ROLE: 'Inactive role.',
    USER_NOT_EXISTS: 'User does not exist.',
    PASSWORD_RESET_SUCESSFULLY: 'Password reset successfully.',
    PASSWORD_CHANGE_SUCESSFULLY: 'Password changed successfully.',
    SETTING_EXISTS: 'Setting name already exists.',
    SUBSCRIPTION_EXISTS: 'Subscription name already exists.',
    USER_EXISTS: 'User name already exists.',
    FORGOT_PASSWORD_LINK_SEND: 'Forgot password link sent.',
    FORGOT_PASSWORD_LINK_EXPIRED: 'This link has been used earlier and is no longer valid.',
    FAILED: 'FAILED.',
    NAME_EXIST: 'The name you entered already exists.',
    NAME_INVALID: 'Name is invalid.',
    VALUE_EXIST: 'Value already exists.',
    ID_INVALID: 'ID is invalid.',
    SUBJECT_EXIST: 'Subject already exists.',
    SUBJECT_INVALID: 'Subject is invalid.',
    EMAIL_EXIST: 'Email already exists.',
    PROJECT_NAME_EXIST: 'Project name already exists',
    PROGRAM_NAME_EXIST: 'Program name already exists',
    NEWPASSWORD_AND_CONFIRMNEWPASSWORD: "New password and confirm password do not match",
    ACCOUNT_NOT_EXIST: 'Account does not exist with the given email.',
    ACCOUNT_DEACTIVATED:
      'We apologize, but your account has been temporarily deactivated. Please contact our support team for further assistance.',
    URL_EXIST: 'URL already exists.',
    TITLE_EXIST: 'Title already exists.',
    MODULE_EXIST: 'Module already exists.',
    RIGHTS_NAME_EXIST: 'Rights already exist for this module.',
    URL_INVALID: 'Invalid URL.',
    DB_DEPENDENCy:
      'Record(s) cannot be deleted, dependency exists with record(s).',
    NAME_CHARACTER_LENGTH: 'The name should not exceed 25 characters.',
    RIGHT_NAME_CHARACTER_LENGTH: 'The name should not exceed 50 characters.',
    ALLOCATE_ONE_RIGHTS: 'Allocate at least one right to the role.',
    RIGHTS_ELEMENT_MUST_NUMBER: 'Array elements in the rights must be numbers',
    ALLOCATE_ONE_TYPE_SERVICE: 'Allocate at least one service to the supplier',
    SERVICE_ELEMENT_MUST_NUMBER:
      'Array elements in the service must be numbers',
    PHONE_NUMBER_VALID: 'The phone number can only contain numbers.',
    PHONE_EXIST: 'Phone number already exists.',
    UPLOAD_TYPES: {
      PROFILE_PICTURE: 'PROFILE_PICTURE',
      AUDIO_FILE: 'AUDIO_FILE',
    },
    TOKEN_VALID: 'Token is valid',
    TIME_FORMAT: 'HH:mm:ss',
    INVALID_CREDENTIAL: 401,
    NOT_FOUND: 404,
    OK: 200,
    CREATED: 201,
    BAD_REQ: 400,
    FORBIDDEN: 403,
    PRECONDITION_FAILED: 412,
    SMTP_ERROR: 501,
    ALREADY_BOOKMARK: 'Already Bookmark',
    BOOKMARK_NOT_FOUND: 'Not found any bookmark',
    FOOTER_CREATED_SUCESSFULLY: "Footer created successfully",
    FOOTER_UPDATED_SUCCESSFULLY: "Footer updated successfully",
    BANNER_CREATED_SUCESSFULLY: "Banner created successfully",
    BANNER_UPDATED_SUCCESSFULLY: "Banner updated successfully",
    INVALID_FILE_TYPE: "Only jpeg, jpg or png file is allowed",
    DESCRIPTION: "Please enter description",
    INTERNAL_SERVER_ERROR_CODE: 500,
    FEEDBACK_SUBMIT: 'Feedback submitted successfully',
    ROLE_NAME: "The role name should not exceed 25 characters.",
    PERMISSION_TYPE: "Please enter permission type",
    SLIDE_CREATED_SUCESSFULLY: "Slide created successfully",
    SLIDE_UPDATED_SUCCESSFULLY: "Slide updated successfully",
    TEMPLATE_CREATED_SUCESSFULLY: "Template created successfully",
    TEMPLATE_UPDATED_SUCESSFULLY: "Template updated successfully",
    PAGE_CREATED_SUCCESSFULLY: "Page created successfully",
    PAGE_UPDATED_SUCCESSFULLY: "Page updated successfully",
    PAGEMASTER_CREATED_SUCCESSFULLY: "Page Master created successfully",
    PAGEMASTER_UPDATED_SUCCESSFULLY: "Page Master updated successfully",
    LAYOUT_CREATED_SUCCESSFULLY: "Layout created successfully",
    LAYOUT_UPDATED_SUCCESSFULLY: "Layout updated successfully",
    SECTION_CREATED_SUCCESSFULLY: "Section created successfully",
    SECTION_UPDATED_SUCCESSFULLY: "Section updated successfully",
    GRIDSECTION_CREATED_SUCCESSFULLY: "Grid Section created successfully",
    GRIDSECTION_UPDATED_SUCCESSFULLY: "Grid Section updated successfully",
    COMPONENT_CREATED_SUCCESSFULLY: "Component created successfully",
    COMPONENT_UPDATED_SUCCESSFULLY: "Component updated successfully",
    TEMPLATE_CREATED_SUCCESSFULLY: "Component created successfully",
    TEMPLATE_UPDATED_SUCCESSFULLY: "Component updated successfully",
    CONTENT_UPDATED_SUCCESSFULLY: "Content updated successfully",
    OTP_SENT: "Otp sent successfully",
    SERVICES_MEDIA_CREATED_SUCESSFULLY: "Services Media created successfully",
    SERVICES_CREATED_SUCESSFULLY: "Services created successfully",
    SERVICES_UPDATED_SUCESSFULLY: "Services updated successfully",
    SERVICES_MEDIA_UPDATED_SUCESSFULLY: "Services Media updated successfully",
    SERVICES_PUBLISHED_SUCESSFULLY: "Services Medias published successfully",
    SERVICES_DELETE_SUCESSFULLY: "Services Medias deleted successfully",
    PAGETESTIMONIAL_CREATED_SUCCESSFULLY: "Page Testimonial created successfully",
    PAGETESTIMONIAL_UPDATED_SUCCESSFULLY: "Page Testimonial updated successfully",
  };
}
